// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "hash", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "qiniu_file_path", Type: field.TypeString},
		{Name: "qiniu_tx_path", Type: field.TypeString},
		{Name: "tags", Type: field.TypeJSON},
		{Name: "user_id", Type: field.TypeString},
		{Name: "wx_id", Type: field.TypeString},
		{Name: "corp_id", Type: field.TypeString},
		{Name: "dept_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
