// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserDemosColumns holds the columns for the "user_demos" table.
	UserDemosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "age", Type: field.TypeString},
		{Name: "gender", Type: field.TypeBool},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserDemosTable holds the schema information for the "user_demos" table.
	UserDemosTable = &schema.Table{
		Name:       "user_demos",
		Columns:    UserDemosColumns,
		PrimaryKey: []*schema.Column{UserDemosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserDemosTable,
	}
)

func init() {
}
