// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"echoDemo/ent/migrate"

	"echoDemo/ent/userdemo"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// UserDemo is the client for interacting with the UserDemo builders.
	UserDemo *UserDemoClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.UserDemo = NewUserDemoClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		UserDemo: NewUserDemoClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		UserDemo: NewUserDemoClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		UserDemo.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.UserDemo.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.UserDemo.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *UserDemoMutation:
		return c.UserDemo.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// UserDemoClient is a client for the UserDemo schema.
type UserDemoClient struct {
	config
}

// NewUserDemoClient returns a client for the UserDemo from the given config.
func NewUserDemoClient(c config) *UserDemoClient {
	return &UserDemoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `userdemo.Hooks(f(g(h())))`.
func (c *UserDemoClient) Use(hooks ...Hook) {
	c.hooks.UserDemo = append(c.hooks.UserDemo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `userdemo.Intercept(f(g(h())))`.
func (c *UserDemoClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserDemo = append(c.inters.UserDemo, interceptors...)
}

// Create returns a builder for creating a UserDemo entity.
func (c *UserDemoClient) Create() *UserDemoCreate {
	mutation := newUserDemoMutation(c.config, OpCreate)
	return &UserDemoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserDemo entities.
func (c *UserDemoClient) CreateBulk(builders ...*UserDemoCreate) *UserDemoCreateBulk {
	return &UserDemoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserDemo.
func (c *UserDemoClient) Update() *UserDemoUpdate {
	mutation := newUserDemoMutation(c.config, OpUpdate)
	return &UserDemoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserDemoClient) UpdateOne(ud *UserDemo) *UserDemoUpdateOne {
	mutation := newUserDemoMutation(c.config, OpUpdateOne, withUserDemo(ud))
	return &UserDemoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserDemoClient) UpdateOneID(id string) *UserDemoUpdateOne {
	mutation := newUserDemoMutation(c.config, OpUpdateOne, withUserDemoID(id))
	return &UserDemoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserDemo.
func (c *UserDemoClient) Delete() *UserDemoDelete {
	mutation := newUserDemoMutation(c.config, OpDelete)
	return &UserDemoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserDemoClient) DeleteOne(ud *UserDemo) *UserDemoDeleteOne {
	return c.DeleteOneID(ud.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserDemoClient) DeleteOneID(id string) *UserDemoDeleteOne {
	builder := c.Delete().Where(userdemo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDemoDeleteOne{builder}
}

// Query returns a query builder for UserDemo.
func (c *UserDemoClient) Query() *UserDemoQuery {
	return &UserDemoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserDemo},
		inters: c.Interceptors(),
	}
}

// Get returns a UserDemo entity by its id.
func (c *UserDemoClient) Get(ctx context.Context, id string) (*UserDemo, error) {
	return c.Query().Where(userdemo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserDemoClient) GetX(ctx context.Context, id string) *UserDemo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserDemoClient) Hooks() []Hook {
	return c.hooks.UserDemo
}

// Interceptors returns the client interceptors.
func (c *UserDemoClient) Interceptors() []Interceptor {
	return c.inters.UserDemo
}

func (c *UserDemoClient) mutate(ctx context.Context, m *UserDemoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserDemoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserDemoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserDemoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDemoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserDemo mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		UserDemo []ent.Hook
	}
	inters struct {
		UserDemo []ent.Interceptor
	}
)
